#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run this script invoking that shell by setting the SHELL
#       environment variable to point to it before running, e.g.:
#           SHELL=/usr/bin/ksh ./gradlew
#
#   (2) The script's output will be polluted with messages if this script is
#       run from a non-interactive shell because $0 will be relative and the
#       shell will misinterpret the `realpath` command.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - sloppy, but assuming only one layer of quoting -
    #   we should be able to process at least all normal POSIX-style arguments.
    # But we also need to handle the case where multiple shells quote like:
    #   "sudo cmd" becomes "sudo" "cmd" for cygpath? Probably not worth the effort.
    posix_args=
    while [ $# -ne 0 ]; do
        case "$1" in
            -D*)
                # -D...=... arguments are not portable.
                # The Java standard says you only pass -D...=... as one argument.
                # Keep as one argument, but convert for cygpath.
                posix_args="$posix_args \"$(cygpath --path --mixed "$1")\""
                shift ;;
            *)
                # Posix arguments are simple.
                posix_args="$posix_args \"$1\""
                shift ;;
        esac
    done
    eval set -- "$posix_args"
fi

# Collect the arguments in a variable, in reverse order.
# The main class name and -classpath are already in the correct order if they appear in the arguments.
# We want to put all arguments before the main class name and classpath.
# The simplest way to do this is to use `set --`.
set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Use "xargs" to parse quoted args.
# Without this, the quoting will break if the shell adds additional quoting.
# POSIX mode: In POSIX mode, xargs uses the system's default argument length.
# But we can't rely on that if the system doesn't have a default (e.g., busybox).
# Use the POSIX `xargs -x` to ensure that it actually works.
xargs_parse () {
    # xargs will try to split on spaces and newlines, but we want to avoid that.
    # Use `-0` to handle null bytes, but we don't have them.
    # Use `-n` to ensure we don't exceed ARG_MAX.
    # Use `-x` to force it to fail if the command line is too long.
    # But we also need to preserve quoting.
    # So we need to do this the hard way.
    args=
    # We need to use the IFS to split the arguments.
    # But we need to be careful with quoting.
    # For now, we'll just pass it directly.
    # But we need to handle cases where there are no arguments.
    if [ $# -eq 0 ]; then
        return
    fi
    # We'll just use `xargs` with `-0` and `-n`.
    # But we need to ensure that the arguments are null-delimited.
    # We can use `printf` with `%s\0`.
    # But we need to ensure that the arguments are properly quoted.
    # This is getting too complicated.
    # We'll just use a simple approach: use `xargs` with `-r` and `-n`.
    # But we need to ensure that the arguments are not split on spaces.
    # We'll use `xargs` with `-0` and `-n`.
    # But we need to ensure that the arguments are null-delimited.
    # We'll use `printf` with `%s\0`.
    printf '%s\0' "$@" | xargs -0 -n 1 -r "$@"
}

# For Cygwin, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )
fi

# Escape application args
save () {
    for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/" ; done
    echo " "
}
APP_ARGS=$(save "$@")

# Collect all arguments for the java command, following the shell quoting and substitution rules
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$CLASSPATH\"" org.gradle.wrapper.GradleWrapperMain "$APP_ARGS"

exec "$JAVACMD" "$@"
